.PHONY:all
all:fa fc pf
fa:FasterArea.cpp
	g++ -o fa FasterArea.cpp -O2
fc:FasterCurve.cpp
	g++ -o fc FasterCurve.cpp -O2
pf:PeakFeatures.cpp
	g++ -o pf PeakFeatures.cpp -O2
clean:
	touch FasterArea.cpp
	touch FasterCurve.cpp
	touch PeakFeatures.cpp
